# Generated by Django 3.0.2 on 2020-02-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='message',
            field=models.TextField(max_length=100),
        ),
    ]
