# Generated by Django 3.0.2 on 2020-02-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_auto_20200211_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='delay',
            field=models.IntegerField(default=0),
        ),
    ]
