# Generated by Django 3.0.2 on 2020-02-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0003_letter_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentletter',
            name='status',
            field=models.CharField(default='не отправлено', max_length=50),
        ),
    ]
